import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { saveInterviewSession } from '../services/interviewStorage';
import { generateInterviewQuestions, fetchAvailableModels } from '../services/interviewService';

const DEFAULT_TECH_STACKS = [
  { id: 'javascript', name: 'JavaScript', icon: 'pi-bolt' },
  { id: 'typescript', name: 'TypeScript', icon: 'pi-file-edit' },
  { id: 'react', name: 'React', icon: 'pi-refresh' },
  { id: 'vue', name: 'Vue.js', icon: 'pi-check-circle' },
  { id: 'angular', name: 'Angular', icon: 'pi-shield' },
  { id: 'node', name: 'Node.js', icon: 'pi-server' },
  { id: 'python', name: 'Python', icon: 'pi-hashtag' },
  { id: 'java', name: 'Java', icon: 'pi-cup' },
  { id: 'go', name: 'Go', icon: 'pi-send' },
  { id: 'rust', name: 'Rust', icon: 'pi-wrench' },
  { id: 'sql', name: 'SQL & Databases', icon: 'pi-database' },
  { id: 'system-design', name: 'System Design', icon: 'pi-sitemap' },
  { id: 'devops', name: 'DevOps', icon: 'pi-cog' },
  { id: 'aws', name: 'AWS/Cloud', icon: 'pi-cloud' },
];

const InterviewPractice = () => {
  const navigate = useNavigate();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isFetchingModels, setIsFetchingModels] = useState(false);
  const [availableModels, setAvailableModels] = useState([]);
  const [error, setError] = useState('');
  
  const [formData, setFormData] = useState({
    candidateName: '',
    company: '',
    techStack: [],
    questionCount: 5,
    difficulty: 'intermediate',
    apiKey: '',
    model: 'gemini-2.5-flash',
    timeLimit: 30,
  });

  useEffect(() => {
    const updateModels = async () => {
      if (formData.apiKey.trim().length < 10) return;
      
      setIsFetchingModels(true);
      try {
        const models = await fetchAvailableModels(formData.apiKey);
        setAvailableModels(models);
        if (models.length > 0 && !models.find(m => m.id === formData.model)) {
          setFormData(prev => ({ ...prev, model: models[0].id }));
        }
      } catch (err) {
        console.error('Failed to fetch models:', err);
        // We don't set the main error state here to avoid interrupting the user 
        // unless they try to start the interview.
      } finally {
        setIsFetchingModels(false);
      }
    };

    const timer = setTimeout(updateModels, 500);
    return () => clearTimeout(timer);
  }, [formData.apiKey]);

  const handleTechStackToggle = (stackId) => {
    setFormData(prev => ({
      ...prev,
      techStack: prev.techStack.includes(stackId)
        ? prev.techStack.filter(id => id !== stackId)
        : [...prev.techStack, stackId]
    }));
    if (error) setError('');
  };

  const validateForm = () => {
    if (!formData.candidateName.trim()) {
      setError('Please enter your name');
      return false;
    }
    if (formData.techStack.length === 0) {
      setError('Please select at least one tech stack');
      return false;
    }
    if (!formData.apiKey.trim()) {
      setError('Gemini API key is required');
      return false;
    }
    return true;
  };

  const handleStartPractice = async () => {
    if (!validateForm()) return;

    setIsGenerating(true);
    setError('');

    try {
      const questions = await generateInterviewQuestions({
        techStack: formData.techStack,
        questionCount: formData.questionCount,
        difficulty: formData.difficulty,
        apiKey: formData.apiKey,
        model: formData.model,
        company: formData.company,
      });

      const session = saveInterviewSession({
        candidateName: formData.candidateName,
        candidateEmail: 'practice@example.com',
        techStack: formData.techStack,
        questionCount: formData.questionCount,
        difficulty: formData.difficulty,
        timeLimit: formData.timeLimit,
        questions: questions,
        notes: `Practice session for ${formData.company || 'any company'} generated by user`,
      });

      navigate(`/tools/ai-interview/candidate/${session.id}`);
    } catch (err) {
      setError(err.message || 'Failed to generate practice interview. Please check your API key.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-4xl">
        <div className="glass-panel rounded-2xl p-8 md:p-12">
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-gradient-to-r from-indigo-600 to-purple-600 mb-6">
              <i className="pi pi-book text-5xl text-white"></i>
            </div>
            <h1 className="text-4xl font-bold text-white mb-4">Interview Practice</h1>
            <p className="text-slate-400 text-lg max-w-2xl mx-auto">
              Prepare for your next big technical interview. Select your stacks and challenge yourself with AI-generated questions.
            </p>
          </div>

          <div className="space-y-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Your Name <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  value={formData.candidateName}
                  onChange={(e) => setFormData(prev => ({ ...prev, candidateName: e.target.value }))}
                  placeholder="Enter your name"
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-700 text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Target Company (Optional)
                </label>
                <input
                  type="text"
                  value={formData.company}
                  onChange={(e) => setFormData(prev => ({ ...prev, company: e.target.value }))}
                  placeholder="e.g. Google, Amazon, Meta"
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-700 text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Gemini API Key <span className="text-red-400">*</span>
                </label>
                <input
                  type="password"
                  value={formData.apiKey}
                  onChange={(e) => setFormData(prev => ({ ...prev, apiKey: e.target.value }))}
                  placeholder="Paste your API key"
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-700 text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Select AI Model
                </label>
                <div className="relative">
                  <select
                    value={formData.model}
                    onChange={(e) => setFormData(prev => ({ ...prev, model: e.target.value }))}
                    disabled={availableModels.length === 0}
                    className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-700 text-white focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {availableModels.length > 0 ? (
                      availableModels.map(model => (
                        <option key={model.id} value={model.id}>{model.name}</option>
                      ))
                    ) : (
                      <option value="">Enter API Key to load models</option>
                    )}
                  </select>
                  {isFetchingModels && (
                    <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
                      <i className="pi pi-spin pi-spinner text-indigo-400"></i>
                    </div>
                  )}
                </div>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-300 mb-3">
                Select Tech Stack <span className="text-red-400">*</span>
              </label>
              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-3">
                {DEFAULT_TECH_STACKS.map(stack => (
                  <button
                    key={stack.id}
                    onClick={() => handleTechStackToggle(stack.id)}
                    className={`p-3 rounded-lg border transition-all text-sm font-medium ${formData.techStack.includes(stack.id)
                        ? 'bg-indigo-600 border-indigo-500 text-white'
                        : 'bg-slate-900/50 border-slate-700 text-slate-300 hover:border-slate-600'
                      }`}
                  >
                    <i className={`pi ${stack.icon} block mb-1`}></i>
                    {stack.name}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Questions
                </label>
                <input
                  type="number"
                  min="1"
                  max="20"
                  value={formData.questionCount}
                  onChange={(e) => setFormData(prev => ({ ...prev, questionCount: parseInt(e.target.value) || 1 }))}
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-700 text-white focus:outline-none focus:ring-1 focus:ring-indigo-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Difficulty
                </label>
                <select
                  value={formData.difficulty}
                  onChange={(e) => setFormData(prev => ({ ...prev, difficulty: e.target.value }))}
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-700 text-white focus:outline-none focus:ring-1 focus:ring-indigo-500"
                >
                  <option value="beginner">Beginner</option>
                  <option value="intermediate">Intermediate</option>
                  <option value="advanced">Advanced</option>
                  <option value="expert">Expert</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Time Limit (min)
                </label>
                <input
                  type="number"
                  min="5"
                  max="180"
                  value={formData.timeLimit}
                  onChange={(e) => setFormData(prev => ({ ...prev, timeLimit: parseInt(e.target.value) || 30 }))}
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-700 text-white focus:outline-none focus:ring-1 focus:ring-indigo-500"
                />
              </div>
            </div>

            {error && (
              <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/20">
                <div className="flex items-center gap-2 text-red-400">
                  <i className="pi pi-exclamation-circle"></i>
                  <span>{error}</span>
                </div>
              </div>
            )}

            <button
              onClick={handleStartPractice}
              disabled={isGenerating}
              className={`w-full py-4 rounded-lg font-bold text-white transition-all ${isGenerating
                  ? 'bg-indigo-600/50 cursor-not-allowed'
                  : 'bg-gradient-to-r from-indigo-600 to-purple-600 hover:shadow-lg hover:scale-[1.02]'
                }`}
            >
              {isGenerating ? (
                <div className="flex items-center justify-center gap-2">
                  <i className="pi pi-spin pi-spinner"></i>
                  <span>Generating Practice Session...</span>
                </div>
              ) : (
                <div className="flex items-center justify-center gap-2">
                  <i className="pi pi-play"></i>
                  <span>Start Practice Interview</span>
                </div>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default InterviewPractice;
